---
title: "Sangonomiya Kokomi"
subtitle: "C0, Postać i bronie lvl 90, Talenty 3x10"
author: "Nephu"
output:
  slidy_presentation:
    fig_height: 7
    fig_width: 11
    highlight: zenburn
---

```{r, include = FALSE}
source("Sangonomiya_Kokomi.R")
library(ggplot2)
```

### Bez efektów z artefaktów
```{r, echo = FALSE}
ggplot(  ) + 
  geom_point( data = filter(dane_razemv2, Set_type == 0), aes( Artifact_type, DMG, color = Rodzaj_ataku, shape = Rodzaj_ataku), size = 2 ) +
  geom_col( data = filter(dane_razemv3, Set_type == 0 & Leczenie == "Burst_Heal"), aes( Artifact_type, DMG, fill = Leczenie ), alpha = 0.75  ) +
  geom_col( data = filter(dane_razemv3, Set_type == 0 & Leczenie == "Bake_reg"), aes( Artifact_type, DMG, fill = Leczenie ), alpha = 0.25  ) +
  ylab("Przeciętne obrażenia") + xlab("Kombinacje artefaktów: Sands, Goblet, Circlet") +
  theme(  legend.position = c( 0.65, 0.15) )+
  guides( color = guide_legend( nrow = 2 ) ) +
  scale_color_brewer( palette = "Dark2") +
  coord_flip() + facet_wrap(~WName)
```

### 4 x Heart of Depth
```{r, echo = FALSE}
ggplot(  ) + 
  geom_point( data = filter(dane_razemv2, Set_type == 1), aes( Artifact_type, DMG, color = Rodzaj_ataku, shape = Rodzaj_ataku), size = 2 ) +
  geom_col( data = filter(dane_razemv3, Set_type == 1 & Leczenie == "Burst_Heal"), aes( Artifact_type, DMG, fill = Leczenie ), alpha = 0.75  ) +
  geom_col( data = filter(dane_razemv3, Set_type == 1 & Leczenie == "Bake_reg"), aes( Artifact_type, DMG, fill = Leczenie ), alpha = 0.25  ) +
  ylab("Przeciętne obrażenia") + xlab("Kombinacje artefaktów: Sands, Goblet, Circlet") +
  theme(  legend.position = c( 0.65, 0.15) )+
  guides( color = guide_legend( nrow = 2 ) ) +
  scale_color_brewer( palette = "Dark2") +
  coord_flip() + facet_wrap(~WName)
```

### 4 x Ocean-Hued Clam
```{r, echo = FALSE}
ggplot(  ) + 
  geom_point( data = filter(dane_razemv2, Set_type == 2), aes( Artifact_type, DMG, color = Rodzaj_ataku, shape = Rodzaj_ataku), size = 2 ) +
  geom_col( data = filter(dane_razemv3, Set_type == 2 & Leczenie == "Burst_Heal"), aes( Artifact_type, DMG, fill = Leczenie ), alpha = 0.75  ) +
  geom_col( data = filter(dane_razemv3, Set_type == 2 & Leczenie == "Bake_reg"), aes( Artifact_type, DMG, fill = Leczenie ), alpha = 0.25  ) +
  ylab("Przeciętne obrażenia") + xlab("Kombinacje artefaktów: Sands, Goblet, Circlet") +
  theme(  legend.position = c( 0.65, 0.15) )+
  guides( color = guide_legend( nrow = 2 ) ) +
  scale_color_brewer( palette = "Dark2") +
  coord_flip() + facet_wrap(~WName)
```
